
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Aug 17 15:31:48 CEST 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 43;
  public static final int CONST = 38;
  public static final int CONTINUE = 41;
  public static final int LPAREN = 32;
  public static final int SEMI = 29;
  public static final int LSEQ = 23;
  public static final int GREQ = 21;
  public static final int RPAREN = 33;
  public static final int AND = 24;
  public static final int LS = 22;
  public static final int OR = 25;
  public static final int BOOL = 44;
  public static final int COMMA = 30;
  public static final int CLASS = 3;
  public static final int INC = 27;
  public static final int DIV = 16;
  public static final int NUM = 42;
  public static final int ASSIGN = 26;
  public static final int IF = 5;
  public static final int DOT = 31;
  public static final int EOF = 0;
  public static final int RETURN = 39;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 15;
  public static final int ADD = 13;
  public static final int MOD = 17;
  public static final int NEQ = 19;
  public static final int IDENT = 45;
  public static final int BREAK = 40;
  public static final int VOID = 12;
  public static final int EQ = 18;
  public static final int LBRACE = 36;
  public static final int ELSE = 6;
  public static final int LSQUARE = 34;
  public static final int READ = 11;
  public static final int RSQUARE = 35;
  public static final int WHILE = 8;
  public static final int RBRACE = 37;
  public static final int EXTENDS = 4;
  public static final int DEC = 28;
  public static final int SUB = 14;
  public static final int GR = 20;
  public static final int PRINT = 10;
  public static final int DO = 7;
}

