
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 13 14:12:18 CEST 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 43;
  public static final int CONST = 41;
  public static final int LPAREN = 35;
  public static final int SEMI = 32;
  public static final int CONTINUE = 4;
  public static final int LSEQ = 26;
  public static final int RPAREN = 36;
  public static final int GREQ = 24;
  public static final int AND = 27;
  public static final int LS = 25;
  public static final int OR = 28;
  public static final int BOOL = 44;
  public static final int COMMA = 33;
  public static final int CLASS = 5;
  public static final int INC = 30;
  public static final int DIV = 19;
  public static final int NUM = 42;
  public static final int ASSIGN = 29;
  public static final int IF = 7;
  public static final int DOT = 34;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 18;
  public static final int ADD = 16;
  public static final int MOD = 20;
  public static final int NEQ = 22;
  public static final int IDENT = 45;
  public static final int BREAK = 3;
  public static final int VOID = 15;
  public static final int EQ = 21;
  public static final int LBRACE = 39;
  public static final int ELSE = 8;
  public static final int LSQUARE = 37;
  public static final int READ = 14;
  public static final int RSQUARE = 38;
  public static final int WHILE = 10;
  public static final int RBRACE = 40;
  public static final int EXTENDS = 6;
  public static final int DEC = 31;
  public static final int SUB = 17;
  public static final int GR = 23;
  public static final int PRINT = 13;
  public static final int DO = 9;
}

